version: '3'

services:
  influxdb:
    image: influxdb:latest
    restart: always
    volumes:
      - /home/arne/docker/grafana-influxdb/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=USER
      - DOCKER_INFLUXDB_INIT_PASSWORD=PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=main-bucket
      - INFLUXDB_LOGGING_LEVEL=debug
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana-oss
    restart: always
    user: "1000"
    ports:
      - 3000:3000
    volumes:
      - /home/arne/docker/grafana-influxdb/grafana/DATA:/var/lib/grafana
